Traceback (most recent call last):
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
container = AppstoreContainer()
repo = container.data.appdata_repo()
dataset = repo.get_dataset()
------------------

----- stderr -----
/bin/sh: 1: /appstore/infrastructure/database/start.sh: not found
----- stderr -----
Database connection failed.
Exception type: type[OperationalError('(pymysql.err.OperationalError) (1049, "Unknown database \'None\'")')]
(pymysql.err.OperationalError) (1049, "Unknown database 'None'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py", line 921, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py", line 1018, in _process_auth
    pkt = self._read_packet()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1049, "Unknown database 'None'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/john/projects/appstore/appstore/infrastructure/database/mysql.py", line 65, in connect
    self._connection = self._engine.connect()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3264, in connect
    return self._connection_cls(self)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    self._dbapi_connection = engine.raw_connection()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
    return self.pool.connect()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 452, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
    rec = pool._do_get()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
    with util.safe_reraise():
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
    return self._create_connection()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
    return _ConnectionRecord(self)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
    self.__connect()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
    with util.safe_reraise():
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 637, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 615, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py", line 353, in __init__
    self.connect()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py", line 633, in connect
    self._request_authentication()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py", line 921, in _request_authentication
    auth_packet = self._process_auth(plugin_name, auth_packet)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py", line 1018, in _process_auth
    pkt = self._read_packet()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/john/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1049, "Unknown database 'None'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOperationalError[0m                          Traceback (most recent call last)
File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py:145[0m, in [0;36mConnection.__init__[0;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[1;32m    144[0m [38;5;28;01mtry[39;00m:
[0;32m--> 145[0m     [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m [43mengine[49m[38;5;241;43m.[39;49m[43mraw_connection[49m[43m([49m[43m)[49m
[1;32m    146[0m [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m err:

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3288[0m, in [0;36mEngine.raw_connection[0;34m(self)[0m
[1;32m   3267[0m [38;5;250m[39m[38;5;124;03m"""Return a "raw" DBAPI connection from the connection pool.[39;00m
[1;32m   3268[0m 
[1;32m   3269[0m [38;5;124;03mThe returned object is a proxied version of the DBAPI[39;00m
[0;32m   (...)[0m
[1;32m   3286[0m 
[1;32m   3287[0m [38;5;124;03m"""[39;00m
[0;32m-> 3288[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mpool[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:452[0m, in [0;36mPool.connect[0;34m(self)[0m
[1;32m    445[0m [38;5;250m[39m[38;5;124;03m"""Return a DBAPI connection from the pool.[39;00m
[1;32m    446[0m 
[1;32m    447[0m [38;5;124;03mThe connection is instrumented such that when its[39;00m
[0;32m   (...)[0m
[1;32m    450[0m 
[1;32m    451[0m [38;5;124;03m"""[39;00m
[0;32m--> 452[0m [38;5;28;01mreturn[39;00m [43m_ConnectionFairy[49m[38;5;241;43m.[39;49m[43m_checkout[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:1267[0m, in [0;36m_ConnectionFairy._checkout[0;34m(cls, pool, threadconns, fairy)[0m
[1;32m   1266[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m fairy:
[0;32m-> 1267[0m     fairy [38;5;241m=[39m [43m_ConnectionRecord[49m[38;5;241;43m.[39;49m[43mcheckout[49m[43m([49m[43mpool[49m[43m)[49m
[1;32m   1269[0m     [38;5;28;01mif[39;00m threadconns [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:716[0m, in [0;36m_ConnectionRecord.checkout[0;34m(cls, pool)[0m
[1;32m    715[0m [38;5;28;01melse[39;00m:
[0;32m--> 716[0m     rec [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_do_get[49m[43m([49m[43m)[49m
[1;32m    718[0m [38;5;28;01mtry[39;00m:

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:169[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    168[0m [38;5;28;01mexcept[39;00m:
[0;32m--> 169[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[1;32m    170[0m         [38;5;28mself[39m[38;5;241m.[39m_dec_overflow()

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:147[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    146[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[0;32m--> 147[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[1;32m    148[0m [38;5;28;01melse[39;00m:

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:167[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    166[0m [38;5;28;01mtry[39;00m:
[0;32m--> 167[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_create_connection[49m[43m([49m[43m)[49m
[1;32m    168[0m [38;5;28;01mexcept[39;00m:

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:393[0m, in [0;36mPool._create_connection[0;34m(self)[0m
[1;32m    391[0m [38;5;250m[39m[38;5;124;03m"""Called by subclasses to create a new ConnectionRecord."""[39;00m
[0;32m--> 393[0m [38;5;28;01mreturn[39;00m [43m_ConnectionRecord[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:678[0m, in [0;36m_ConnectionRecord.__init__[0;34m(self, pool, connect)[0m
[1;32m    677[0m [38;5;28;01mif[39;00m connect:
[0;32m--> 678[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__connect[49m[43m([49m[43m)[49m
[1;32m    679[0m [38;5;28mself[39m[38;5;241m.[39mfinalize_callback [38;5;241m=[39m deque()

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:902[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    901[0m [38;5;28;01mexcept[39;00m [38;5;167;01mBaseException[39;00m [38;5;28;01mas[39;00m e:
[0;32m--> 902[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[1;32m    903[0m         pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mError on connect(): [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m, e)

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:147[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    146[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[0;32m--> 147[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[1;32m    148[0m [38;5;28;01melse[39;00m:

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:898[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    897[0m [38;5;28mself[39m[38;5;241m.[39mstarttime [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 898[0m [38;5;28mself[39m[38;5;241m.[39mdbapi_connection [38;5;241m=[39m connection [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_invoke_creator[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m
[1;32m    899[0m pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mCreated new connection [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m, connection)

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/create.py:637[0m, in [0;36mcreate_engine.<locals>.connect[0;34m(connection_record)[0m
[1;32m    635[0m             [38;5;28;01mreturn[39;00m connection
[0;32m--> 637[0m [38;5;28;01mreturn[39;00m [43mdialect[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/default.py:615[0m, in [0;36mDefaultDialect.connect[0;34m(self, *cargs, **cparams)[0m
[1;32m    613[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m, [38;5;241m*[39mcargs, [38;5;241m*[39m[38;5;241m*[39mcparams):
[1;32m    614[0m     [38;5;66;03m# inherits the docstring from interfaces.Dialect.connect[39;00m
[0;32m--> 615[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mloaded_dbapi[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py:353[0m, in [0;36mConnection.__init__[0;34m(self, user, password, host, database, unix_socket, port, charset, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, read_default_group, autocommit, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key, ssl, ssl_ca, ssl_cert, ssl_disabled, ssl_key, ssl_verify_cert, ssl_verify_identity, compress, named_pipe, passwd, db)[0m
[1;32m    352[0m [38;5;28;01melse[39;00m:
[0;32m--> 353[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py:633[0m, in [0;36mConnection.connect[0;34m(self, sock)[0m
[1;32m    632[0m [38;5;28mself[39m[38;5;241m.[39m_get_server_information()
[0;32m--> 633[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_request_authentication[49m[43m([49m[43m)[49m
[1;32m    635[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39msql_mode [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py:921[0m, in [0;36mConnection._request_authentication[0;34m(self)[0m
[1;32m    917[0m [38;5;28;01mif[39;00m (
[1;32m    918[0m     [38;5;28mself[39m[38;5;241m.[39mserver_capabilities [38;5;241m&[39m CLIENT[38;5;241m.[39mPLUGIN_AUTH
[1;32m    919[0m     [38;5;129;01mand[39;00m plugin_name [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m    920[0m ):
[0;32m--> 921[0m     auth_packet [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_process_auth[49m[43m([49m[43mplugin_name[49m[43m,[49m[43m [49m[43mauth_packet[49m[43m)[49m
[1;32m    922[0m [38;5;28;01melse[39;00m:
[1;32m    923[0m     [38;5;66;03m# send legacy handshake[39;00m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py:1018[0m, in [0;36mConnection._process_auth[0;34m(self, plugin_name, auth_packet)[0m
[1;32m   1017[0m [38;5;28mself[39m[38;5;241m.[39mwrite_packet(data)
[0;32m-> 1018[0m pkt [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_read_packet[49m[43m([49m[43m)[49m
[1;32m   1019[0m pkt[38;5;241m.[39mcheck_error()

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py:725[0m, in [0;36mConnection._read_packet[0;34m(self, packet_type)[0m
[1;32m    724[0m         [38;5;28mself[39m[38;5;241m.[39m_result[38;5;241m.[39munbuffered_active [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[0;32m--> 725[0m     [43mpacket[49m[38;5;241;43m.[39;49m[43mraise_for_error[49m[43m([49m[43m)[49m
[1;32m    726[0m [38;5;28;01mreturn[39;00m packet

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/protocol.py:221[0m, in [0;36mMysqlPacket.raise_for_error[0;34m(self)[0m
[1;32m    220[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124merrno =[39m[38;5;124m"[39m, errno)
[0;32m--> 221[0m [43merr[49m[38;5;241;43m.[39;49m[43mraise_mysql_exception[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_data[49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/err.py:143[0m, in [0;36mraise_mysql_exception[0;34m(data)[0m
[1;32m    142[0m     errorclass [38;5;241m=[39m InternalError [38;5;28;01mif[39;00m errno [38;5;241m<[39m [38;5;241m1000[39m [38;5;28;01melse[39;00m OperationalError
[0;32m--> 143[0m [38;5;28;01mraise[39;00m errorclass(errno, errval)

[0;31mOperationalError[0m: (1049, "Unknown database 'None'")

The above exception was the direct cause of the following exception:

[0;31mOperationalError[0m                          Traceback (most recent call last)
Cell [0;32mIn[3], line 2[0m
[1;32m      1[0m container [38;5;241m=[39m AppstoreContainer()
[0;32m----> 2[0m repo [38;5;241m=[39m [43mcontainer[49m[38;5;241;43m.[39;49m[43mdata[49m[38;5;241;43m.[39;49m[43mappdata_repo[49m[43m([49m[43m)[49m
[1;32m      3[0m dataset [38;5;241m=[39m repo[38;5;241m.[39mget_dataset()

File [0;32msrc/dependency_injector/providers.pyx:225[0m, in [0;36mdependency_injector.providers.Provider.__call__[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pyx:3049[0m, in [0;36mdependency_injector.providers.Singleton._provide[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pxd:650[0m, in [0;36mdependency_injector.providers.__factory_call[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pxd:577[0m, in [0;36mdependency_injector.providers.__call[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pxd:445[0m, in [0;36mdependency_injector.providers.__provide_keyword_args[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pxd:365[0m, in [0;36mdependency_injector.providers.__get_value[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pyx:225[0m, in [0;36mdependency_injector.providers.Provider.__call__[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pyx:3049[0m, in [0;36mdependency_injector.providers.Singleton._provide[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pxd:650[0m, in [0;36mdependency_injector.providers.__factory_call[0;34m()[0m

File [0;32msrc/dependency_injector/providers.pxd:608[0m, in [0;36mdependency_injector.providers.__call[0;34m()[0m

File [0;32m~/projects/appstore/appstore/infrastructure/database/mysql.py:55[0m, in [0;36mMySQLDatabase.__init__[0;34m(self, name)[0m
[1;32m     53[0m [38;5;28mself[39m[38;5;241m.[39m_name [38;5;241m=[39m name
[1;32m     54[0m [38;5;28mself[39m[38;5;241m.[39m_connection_string [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_get_connection_string()
[0;32m---> 55[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m~/projects/appstore/appstore/infrastructure/database/mysql.py:65[0m, in [0;36mMySQLDatabase.connect[0;34m(self, autocommit)[0m
[1;32m     63[0m [38;5;28;01mtry[39;00m:
[1;32m     64[0m     [38;5;28mself[39m[38;5;241m.[39m_engine [38;5;241m=[39m sqlalchemy[38;5;241m.[39mcreate_engine([38;5;28mself[39m[38;5;241m.[39m_connection_string)
[0;32m---> 65[0m     [38;5;28mself[39m[38;5;241m.[39m_connection [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engine[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m
[1;32m     66[0m     [38;5;28;01mif[39;00m autocommit [38;5;129;01mis[39;00m [38;5;28;01mTrue[39;00m:
[1;32m     67[0m         [38;5;28mself[39m[38;5;241m.[39m_connection[38;5;241m.[39mexecution_options(isolation_level[38;5;241m=[39m[38;5;124m"[39m[38;5;124mAUTOCOMMIT[39m[38;5;124m"[39m)

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3264[0m, in [0;36mEngine.connect[0;34m(self)[0m
[1;32m   3241[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m Connection:
[1;32m   3242[0m [38;5;250m    [39m[38;5;124;03m"""Return a new :class:`_engine.Connection` object.[39;00m
[1;32m   3243[0m 
[1;32m   3244[0m [38;5;124;03m    The :class:`_engine.Connection` acts as a Python context manager, so[39;00m
[0;32m   (...)[0m
[1;32m   3261[0m 
[1;32m   3262[0m [38;5;124;03m    """[39;00m
[0;32m-> 3264[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_connection_cls[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py:147[0m, in [0;36mConnection.__init__[0;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[1;32m    145[0m         [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m engine[38;5;241m.[39mraw_connection()
[1;32m    146[0m     [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m err:
[0;32m--> 147[0m         [43mConnection[49m[38;5;241;43m.[39;49m[43m_handle_dbapi_exception_noconnection[49m[43m([49m
[1;32m    148[0m [43m            [49m[43merr[49m[43m,[49m[43m [49m[43mdialect[49m[43m,[49m[43m [49m[43mengine[49m
[1;32m    149[0m [43m        [49m[43m)[49m
[1;32m    150[0m         [38;5;28;01mraise[39;00m
[1;32m    151[0m [38;5;28;01melse[39;00m:

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py:2426[0m, in [0;36mConnection._handle_dbapi_exception_noconnection[0;34m(cls, e, dialect, engine, is_disconnect, invalidate_pool_on_disconnect, is_pre_ping)[0m
[1;32m   2424[0m [38;5;28;01melif[39;00m should_wrap:
[1;32m   2425[0m     [38;5;28;01massert[39;00m sqlalchemy_exception [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[0;32m-> 2426[0m     [38;5;28;01mraise[39;00m sqlalchemy_exception[38;5;241m.[39mwith_traceback(exc_info[[38;5;241m2[39m]) [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m
[1;32m   2427[0m [38;5;28;01melse[39;00m:
[1;32m   2428[0m     [38;5;28;01massert[39;00m exc_info[[38;5;241m1[39m] [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py:145[0m, in [0;36mConnection.__init__[0;34m(self, engine, connection, _has_events, _allow_revalidate, _allow_autobegin)[0m
[1;32m    143[0m [38;5;28;01mif[39;00m connection [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    144[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 145[0m         [38;5;28mself[39m[38;5;241m.[39m_dbapi_connection [38;5;241m=[39m [43mengine[49m[38;5;241;43m.[39;49m[43mraw_connection[49m[43m([49m[43m)[49m
[1;32m    146[0m     [38;5;28;01mexcept[39;00m dialect[38;5;241m.[39mloaded_dbapi[38;5;241m.[39mError [38;5;28;01mas[39;00m err:
[1;32m    147[0m         Connection[38;5;241m.[39m_handle_dbapi_exception_noconnection(
[1;32m    148[0m             err, dialect, engine
[1;32m    149[0m         )

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/base.py:3288[0m, in [0;36mEngine.raw_connection[0;34m(self)[0m
[1;32m   3266[0m [38;5;28;01mdef[39;00m [38;5;21mraw_connection[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m PoolProxiedConnection:
[1;32m   3267[0m [38;5;250m    [39m[38;5;124;03m"""Return a "raw" DBAPI connection from the connection pool.[39;00m
[1;32m   3268[0m 
[1;32m   3269[0m [38;5;124;03m    The returned object is a proxied version of the DBAPI[39;00m
[0;32m   (...)[0m
[1;32m   3286[0m 
[1;32m   3287[0m [38;5;124;03m    """[39;00m
[0;32m-> 3288[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mpool[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:452[0m, in [0;36mPool.connect[0;34m(self)[0m
[1;32m    444[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m PoolProxiedConnection:
[1;32m    445[0m [38;5;250m    [39m[38;5;124;03m"""Return a DBAPI connection from the pool.[39;00m
[1;32m    446[0m 
[1;32m    447[0m [38;5;124;03m    The connection is instrumented such that when its[39;00m
[0;32m   (...)[0m
[1;32m    450[0m 
[1;32m    451[0m [38;5;124;03m    """[39;00m
[0;32m--> 452[0m     [38;5;28;01mreturn[39;00m [43m_ConnectionFairy[49m[38;5;241;43m.[39;49m[43m_checkout[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:1267[0m, in [0;36m_ConnectionFairy._checkout[0;34m(cls, pool, threadconns, fairy)[0m
[1;32m   1259[0m [38;5;129m@classmethod[39m
[1;32m   1260[0m [38;5;28;01mdef[39;00m [38;5;21m_checkout[39m(
[1;32m   1261[0m     [38;5;28mcls[39m,
[0;32m   (...)[0m
[1;32m   1264[0m     fairy: Optional[_ConnectionFairy] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m   1265[0m ) [38;5;241m-[39m[38;5;241m>[39m _ConnectionFairy:
[1;32m   1266[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m fairy:
[0;32m-> 1267[0m         fairy [38;5;241m=[39m [43m_ConnectionRecord[49m[38;5;241;43m.[39;49m[43mcheckout[49m[43m([49m[43mpool[49m[43m)[49m
[1;32m   1269[0m         [38;5;28;01mif[39;00m threadconns [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m   1270[0m             threadconns[38;5;241m.[39mcurrent [38;5;241m=[39m weakref[38;5;241m.[39mref(fairy)

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:716[0m, in [0;36m_ConnectionRecord.checkout[0;34m(cls, pool)[0m
[1;32m    714[0m     rec [38;5;241m=[39m cast(_ConnectionRecord, pool[38;5;241m.[39m_do_get())
[1;32m    715[0m [38;5;28;01melse[39;00m:
[0;32m--> 716[0m     rec [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_do_get[49m[43m([49m[43m)[49m
[1;32m    718[0m [38;5;28;01mtry[39;00m:
[1;32m    719[0m     dbapi_connection [38;5;241m=[39m rec[38;5;241m.[39mget_connection()

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:169[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    167[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_create_connection()
[1;32m    168[0m [38;5;28;01mexcept[39;00m:
[0;32m--> 169[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[1;32m    170[0m         [38;5;28mself[39m[38;5;241m.[39m_dec_overflow()
[1;32m    171[0m     [38;5;28;01mraise[39;00m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:147[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    145[0m     [38;5;28;01massert[39;00m exc_value [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m    146[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[0;32m--> 147[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[1;32m    148[0m [38;5;28;01melse[39;00m:
[1;32m    149[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/impl.py:167[0m, in [0;36mQueuePool._do_get[0;34m(self)[0m
[1;32m    165[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_inc_overflow():
[1;32m    166[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 167[0m         [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_create_connection[49m[43m([49m[43m)[49m
[1;32m    168[0m     [38;5;28;01mexcept[39;00m:
[1;32m    169[0m         [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:393[0m, in [0;36mPool._create_connection[0;34m(self)[0m
[1;32m    390[0m [38;5;28;01mdef[39;00m [38;5;21m_create_connection[39m([38;5;28mself[39m) [38;5;241m-[39m[38;5;241m>[39m ConnectionPoolEntry:
[1;32m    391[0m [38;5;250m    [39m[38;5;124;03m"""Called by subclasses to create a new ConnectionRecord."""[39;00m
[0;32m--> 393[0m     [38;5;28;01mreturn[39;00m [43m_ConnectionRecord[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:678[0m, in [0;36m_ConnectionRecord.__init__[0;34m(self, pool, connect)[0m
[1;32m    676[0m [38;5;28mself[39m[38;5;241m.[39m__pool [38;5;241m=[39m pool
[1;32m    677[0m [38;5;28;01mif[39;00m connect:
[0;32m--> 678[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__connect[49m[43m([49m[43m)[49m
[1;32m    679[0m [38;5;28mself[39m[38;5;241m.[39mfinalize_callback [38;5;241m=[39m deque()

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:902[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    900[0m     [38;5;28mself[39m[38;5;241m.[39mfresh [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m    901[0m [38;5;28;01mexcept[39;00m [38;5;167;01mBaseException[39;00m [38;5;28;01mas[39;00m e:
[0;32m--> 902[0m     [38;5;28;01mwith[39;00m util[38;5;241m.[39msafe_reraise():
[1;32m    903[0m         pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mError on connect(): [39m[38;5;132;01m%s[39;00m[38;5;124m"[39m, e)
[1;32m    904[0m [38;5;28;01melse[39;00m:
[1;32m    905[0m     [38;5;66;03m# in SQLAlchemy 1.4 the first_connect event is not used by[39;00m
[1;32m    906[0m     [38;5;66;03m# the engine, so this will usually not be set[39;00m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py:147[0m, in [0;36msafe_reraise.__exit__[0;34m(self, type_, value, traceback)[0m
[1;32m    145[0m     [38;5;28;01massert[39;00m exc_value [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m    146[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m
[0;32m--> 147[0m     [38;5;28;01mraise[39;00m exc_value[38;5;241m.[39mwith_traceback(exc_tb)
[1;32m    148[0m [38;5;28;01melse[39;00m:
[1;32m    149[0m     [38;5;28mself[39m[38;5;241m.[39m_exc_info [38;5;241m=[39m [38;5;28;01mNone[39;00m  [38;5;66;03m# remove potential circular references[39;00m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/pool/base.py:898[0m, in [0;36m_ConnectionRecord.__connect[0;34m(self)[0m
[1;32m    896[0m [38;5;28;01mtry[39;00m:
[1;32m    897[0m     [38;5;28mself[39m[38;5;241m.[39mstarttime [38;5;241m=[39m time[38;5;241m.[39mtime()
[0;32m--> 898[0m     [38;5;28mself[39m[38;5;241m.[39mdbapi_connection [38;5;241m=[39m connection [38;5;241m=[39m [43mpool[49m[38;5;241;43m.[39;49m[43m_invoke_creator[49m[43m([49m[38;5;28;43mself[39;49m[43m)[49m
[1;32m    899[0m     pool[38;5;241m.[39mlogger[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mCreated new connection [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m, connection)
[1;32m    900[0m     [38;5;28mself[39m[38;5;241m.[39mfresh [38;5;241m=[39m [38;5;28;01mTrue[39;00m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/create.py:637[0m, in [0;36mcreate_engine.<locals>.connect[0;34m(connection_record)[0m
[1;32m    634[0m         [38;5;28;01mif[39;00m connection [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    635[0m             [38;5;28;01mreturn[39;00m connection
[0;32m--> 637[0m [38;5;28;01mreturn[39;00m [43mdialect[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/sqlalchemy/engine/default.py:615[0m, in [0;36mDefaultDialect.connect[0;34m(self, *cargs, **cparams)[0m
[1;32m    613[0m [38;5;28;01mdef[39;00m [38;5;21mconnect[39m([38;5;28mself[39m, [38;5;241m*[39mcargs, [38;5;241m*[39m[38;5;241m*[39mcparams):
[1;32m    614[0m     [38;5;66;03m# inherits the docstring from interfaces.Dialect.connect[39;00m
[0;32m--> 615[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mloaded_dbapi[49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[38;5;241;43m*[39;49m[43mcargs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mcparams[49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py:353[0m, in [0;36mConnection.__init__[0;34m(self, user, password, host, database, unix_socket, port, charset, sql_mode, read_default_file, conv, use_unicode, client_flag, cursorclass, init_command, connect_timeout, read_default_group, autocommit, local_infile, max_allowed_packet, defer_connect, auth_plugin_map, read_timeout, write_timeout, bind_address, binary_prefix, program_name, server_public_key, ssl, ssl_ca, ssl_cert, ssl_disabled, ssl_key, ssl_verify_cert, ssl_verify_identity, compress, named_pipe, passwd, db)[0m
[1;32m    351[0m     [38;5;28mself[39m[38;5;241m.[39m_sock [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m    352[0m [38;5;28;01melse[39;00m:
[0;32m--> 353[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mconnect[49m[43m([49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py:633[0m, in [0;36mConnection.connect[0;34m(self, sock)[0m
[1;32m    630[0m [38;5;28mself[39m[38;5;241m.[39m_next_seq_id [38;5;241m=[39m [38;5;241m0[39m
[1;32m    632[0m [38;5;28mself[39m[38;5;241m.[39m_get_server_information()
[0;32m--> 633[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_request_authentication[49m[43m([49m[43m)[49m
[1;32m    635[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39msql_mode [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m    636[0m     c [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mcursor()

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py:921[0m, in [0;36mConnection._request_authentication[0;34m(self)[0m
[1;32m    916[0m plugin_name [38;5;241m=[39m auth_packet[38;5;241m.[39mread_string()
[1;32m    917[0m [38;5;28;01mif[39;00m (
[1;32m    918[0m     [38;5;28mself[39m[38;5;241m.[39mserver_capabilities [38;5;241m&[39m CLIENT[38;5;241m.[39mPLUGIN_AUTH
[1;32m    919[0m     [38;5;129;01mand[39;00m plugin_name [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m    920[0m ):
[0;32m--> 921[0m     auth_packet [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_process_auth[49m[43m([49m[43mplugin_name[49m[43m,[49m[43m [49m[43mauth_packet[49m[43m)[49m
[1;32m    922[0m [38;5;28;01melse[39;00m:
[1;32m    923[0m     [38;5;66;03m# send legacy handshake[39;00m
[1;32m    924[0m     data [38;5;241m=[39m _auth[38;5;241m.[39mscramble_old_password([38;5;28mself[39m[38;5;241m.[39mpassword, [38;5;28mself[39m[38;5;241m.[39msalt) [38;5;241m+[39m [38;5;124mb[39m[38;5;124m"[39m[38;5;130;01m\0[39;00m[38;5;124m"[39m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py:1018[0m, in [0;36mConnection._process_auth[0;34m(self, plugin_name, auth_packet)[0m
[1;32m   1013[0m     [38;5;28;01mraise[39;00m err[38;5;241m.[39mOperationalError(
[1;32m   1014[0m         [38;5;241m2059[39m, [38;5;124m"[39m[38;5;124mAuthentication plugin [39m[38;5;124m'[39m[38;5;132;01m%s[39;00m[38;5;124m'[39m[38;5;124m not configured[39m[38;5;124m"[39m [38;5;241m%[39m plugin_name
[1;32m   1015[0m     )
[1;32m   1017[0m [38;5;28mself[39m[38;5;241m.[39mwrite_packet(data)
[0;32m-> 1018[0m pkt [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_read_packet[49m[43m([49m[43m)[49m
[1;32m   1019[0m pkt[38;5;241m.[39mcheck_error()
[1;32m   1020[0m [38;5;28;01mreturn[39;00m pkt

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/connections.py:725[0m, in [0;36mConnection._read_packet[0;34m(self, packet_type)[0m
[1;32m    723[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_result [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m [38;5;28mself[39m[38;5;241m.[39m_result[38;5;241m.[39munbuffered_active [38;5;129;01mis[39;00m [38;5;28;01mTrue[39;00m:
[1;32m    724[0m         [38;5;28mself[39m[38;5;241m.[39m_result[38;5;241m.[39munbuffered_active [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[0;32m--> 725[0m     [43mpacket[49m[38;5;241;43m.[39;49m[43mraise_for_error[49m[43m([49m[43m)[49m
[1;32m    726[0m [38;5;28;01mreturn[39;00m packet

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/protocol.py:221[0m, in [0;36mMysqlPacket.raise_for_error[0;34m(self)[0m
[1;32m    219[0m [38;5;28;01mif[39;00m DEBUG:
[1;32m    220[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124merrno =[39m[38;5;124m"[39m, errno)
[0;32m--> 221[0m [43merr[49m[38;5;241;43m.[39;49m[43mraise_mysql_exception[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_data[49m[43m)[49m

File [0;32m~/anaconda3/envs/appstore/lib/python3.10/site-packages/pymysql/err.py:143[0m, in [0;36mraise_mysql_exception[0;34m(data)[0m
[1;32m    141[0m [38;5;28;01mif[39;00m errorclass [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    142[0m     errorclass [38;5;241m=[39m InternalError [38;5;28;01mif[39;00m errno [38;5;241m<[39m [38;5;241m1000[39m [38;5;28;01melse[39;00m OperationalError
[0;32m--> 143[0m [38;5;28;01mraise[39;00m errorclass(errno, errval)

[0;31mOperationalError[0m: (pymysql.err.OperationalError) (1049, "Unknown database 'None'")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

